// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackmaniaWebsiteAPInew.Data;

#nullable disable

namespace TrackmaniaWebsiteAPInew.Migrations
{
    [DbContext(typeof(MapInfoDbContext))]
    partial class MapInfoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TrackmaniaWebsiteAPInew.Models.MapInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AllMapsInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "First map "
                        },
                        new
                        {
                            Id = 2,
                            Title = "Second map "
                        },
                        new
                        {
                            Id = 3,
                            Title = "Third map "
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
